# Generated by Django 4.0.5 on 2022-06-22 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppHospital', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paciente',
            new_name='Pacientes',
        ),
    ]
